# Generated by Django 3.1.3 on 2020-11-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingrediente1', models.CharField(max_length=50)),
                ('Ingrediente2', models.CharField(max_length=50)),
                ('Ingrediente3', models.CharField(max_length=50)),
                ('Ingrediente4', models.CharField(max_length=50)),
                ('Ingrediente5', models.CharField(max_length=50)),
                ('Ingrediente6', models.CharField(max_length=50)),
                ('trago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.trago')),
            ],
        ),
        migrations.DeleteModel(
            name='Miembro',
        ),
    ]
