# Generated by Django 3.1.3 on 2020-11-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.TextField()),
                ('preparacion', models.TextField()),
                ('trago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.trago')),
            ],
        ),
    ]
